spring:
  application:
    name: cchy25

  output:
    ansi:
      enabled: ALWAYS

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://localhost:3306/cchy"
    username: root
    password: 25cchyroot

  jpa:
    hibernate:
      ddl-auto: create-drop

jwt:
  secret-key: "1231234guihbasd89y12h2b3kjasjd09u12h3j12312asoifoih123"
  access-token-exp: 900