spring:
  application:
    name: cchy25

  output:
    ansi:
      enabled: ALWAYS

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://${DB_URL}/cchy"
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
      ddl-auto: create

  data:
    elasticsearch:
      uris: ${ES_URL}


jwt:
  secret-key: ${JWT_KEY}
  access-token-exp: 900
