spring:
  application:
    name: cchy25

  output:
    ansi:
      enabled: ALWAYS

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://localhost:3306/cchy"
    username: root
    password: 25cchyroot

  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
      ddl-auto: update
#    show-sql: true
#    properties:
#      hibernate.format_sql: true
#
#logging:
#  level:
#    org.hibernate.SQL: debug
#    org.hibernate.type.descriptor.sql: trace

  data:
    elasticsearch:
      uris: "http://localhost:9200"

  batch:
    jdbc:
      initialize-schema: always # MySQL과 같은 외부 데이터베이스를 사용하는 경우 'always'로 설정합니다.

jwt:
  secret-key: "1231234guihbasd89y12h2b3kjasjd09u12h3j12312asoifoih123"
  access-token-exp: 900