name: 빌드 및 배포

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:  #ghcr용
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3 #코드 러너에 체크아웃

      - name: Set up JDK 21
        uses: actions/setup-java@v3 #jdk 설정
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'gradle' # 의존성 캐싱

      - name: Build with Gradle # 빌드
        run: |
          chmod +x ./gradlew
          ./gradlew clean build --no-daemon

      - name: Build Docker image # 이미지 빌드
        run: |
          docker build -t qstart:latest .
          
          # - name: Login to DockerHub
          #   uses: docker/login-action@v2
          #   with:
          #     username: ${{ secrets.DOCKER_USERNAME }}
          #     password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Login to GHCR
        run: |
          echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push Docker image to GHCR
        run: |
          docker tag qstart:latest ghcr.io/${{ github.repository_owner }}/qstart:latest
          docker push ghcr.io/${{ github.repository_owner }}/qstart:latest

      # - name: Push Docker image
      #   run: |
      #     docker tag myapp:latest your-dockerhub-id/myapp:latest |
      #     docker push your-dockerhub-id/myapp:latest

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            docker pull ghcr.io/${{ github.repository_owner }}/qstart:latest
            docker stop qstart-container || true
            docker rm qstart-container || true
            docker run -d --name qstart-container -p 8080:8080 ghcr.io/${{ github.repository_owner }}/qstart:latest
